### ISSUE TITLE
Meetup 2019.05

### ISSUE THREAD

**Issue by zerok** [gograz/planning#1]
- [ ] Themen sammeln
- [ ] https://www.meetup.com/Graz-Open-Source-Meetup/events/lbbhjlyzhbcc/ auf Meetup announcen
- [x] Website aktualisieren
- [x] Termin auf Twitter posten
- [x] Termin auf Mastodon posten

**Comment by m12r** [comment]
@zerok Ich werde am Dienstag voraussichtlich nun doch da sein können.
