### ISSUE TITLE
Contact SecurityStammtisch regarding new date

### ISSUE THREAD

**Issue by zerok** [gograz/planning#9]

**Comment by meisterluk** [comment]
They meet monthly on the second Tuesday. They will keep it that way (routine since years) and the intersection with GoGraz is supposedly small (STG is mainly sysadmins, GoGraz is mainly dev).

https://michael-prokop.at/stg/

**Comment by zerok** [comment]
Awesome, thank you :) So we don't actually have a scheduling conflict :)
